### ISSUE TITLE
Executive Summary

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#12]
Going to be using SharedLatex for preparing this document.

[Executive Summary Draft](https://www.sharelatex.com/project/5791146e197f2f1913025b8b)

**Comment by rozina1** [comment]
i have started this

**Comment by Nnichole222** [comment]
We agreed that the first half of the paper will be done in word. After the midterm, Uma said she would try and up load it to latex.  I said I'd help her and learn the program.

**Comment by austinvernsonger** [comment]
When did we agree? Cause this is new to me..

**Comment by Nnichole222** [comment]
Correct it is new. We agreed yesterday.

**Comment by austinvernsonger** [comment]
No decisions should of been made.

**Comment by vbruno81** [comment]
Shit

**Comment by austinvernsonger** [comment]
Fuck

Very Respectfully,

Austin Vern Songer

On Tue, Aug 23, 2016 at 7:07 PM -0500, "vbruno81" notifications@github.com wrote:

Shit

**Comment by vbruno81** [comment]
Balls Deeeeep 

dripping wet.

Love Vince

**Comment by austinvernsonger** [comment]
Slob on my knob, like corn on the cob 

Very Respectfully,

Austin Vern Songer

On Tue, Aug 23, 2016 at 7:14 PM -0500, "vbruno81" notifications@github.com wrote:

Balls Deeeeep 

dripping wet.

Love Vince
