### ISSUE TITLE
Customer Support

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#15]
Find 5 Open Source Customer Support Systems

**Comment by vbruno81** [comment]
https://www.uservoice.com/
https://freshdesk.com/
http://www.spiceworks.com/free-help-desk-software/
http://osticket.com/
https://www.otrs.com/otrs-free-help-desk/open-source/

**Comment by austinvernsonger** [comment]
Going to use slack. This will allow Dana to be able to chat directly.

#21
