### ISSUE TITLE
Mautic marketing automation platform

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#16]
Find the requirements for marketing automation platform

**Comment by Umatrika** [comment]
A good post to know about Mautic. https://www.quora.com/What-is-your-experience-with-using-Mautic. 

@austinvernsonger : One of the users says: "**MAUTIC is not entirely free! For the hosted account, it is free for only upto 2500 leads, just 500 more than Mailchimp. But it is cheaper than many other services...but cheap should never be the deciding factor!**"
Read Pramod George's answer.

**Comment by Umatrika** [comment]
**Requirements**: https://www.mautic.org/download/requirements/

**Issue with chrome browser**. I hope its fixed. https://www.mautic.org/community/index.php/215-mautic-crashing-ram-requirements/0

**Limits of hosted version:** Their service is free forever, but it has limits. Amount of contacts is limited to 2,500, only one user can be created and integrations are limited to 3. Fortunately, there are paid plans as well. Pro plan has unlimited leads, 5 integrations and 2 users. It also has the option to use a custom domain. (I am not sure if we planning for hosted or self hosted versions)

**Comment by Umatrika** [comment]
Implementing Mautic API:

http://johnlinhart.com/blog/implementing-mautic-api
https://github.com/mautic/api-library#using-the-mautic-api-library

**Comment by austinvernsonger** [comment]
It is completely free with manipulation of the code.  But she will not longer need this because Zenbership can take care of marketing automation.
