### ISSUE TITLE
Customer-Relationship Management System - Zenbership

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#17]
~~[KillBill](http://killbill.io)~~
[Zenbership](https://www.zenbership.com)
### CRM & Account Management
- Manage Contacts : Manage a custom database of contacts that can be expanded to meet your needs
- Manage Accounts : Groups contacts and members into accounts and manage entire accounts collectively
### Membership Management
- "Hands-Free" Management : Automate online registrations, payments, renewals, invoices, account updates, lost password recovery, event planning and reminders, and e-mail campaigns
- Automated Due Collection : Membership dues can easily be collected online through the Zenbership subscription system
### eCommerce Tools
- Payment Gateway Integration : Integrated with a number of payment gateways, including popular solutions like Stripe, Authorize.net, and PayPal
- Multiple Product Types : The shopping cart support multiple products types, including digital products, physical products, subscriptions products, and trial products
### Subscriptions & Dues
- Flexible Billing Intervals : Charge subscriptions at regular intervals or on the same day every month or year, optionally setting a maximum number of renewals
- Online Management : Members and users alike can easily manage subscriptions directly from their online management portal
### Invoicing
- Flexible Pricing Options : Create invoices with flexible options, including time based components, products found directly within the shopping cart, and even invoice credits
- Easy Invoice Creation : Allow users to request invoices directly from the shopping cart or when registering for an event
- What does it take to make this work?
  - Requirements
  - Configurations
  - API’s
  - And any additional information you can provide.

**Comment by vbruno81** [comment]
http://killbill.io/blog/kill-bill-0-14-0-released/
https://github.com/killbill/killbill-avatax-plugin
https://github.com/killbill/killbill-email-notifications-plugin

**Comment by Umatrika** [comment]
@austinvernsonger : So are we dropping KillBill and using Zenbership payment gateway?

**Comment by austinvernsonger** [comment]
@Umatrika Correct
