### ISSUE TITLE
What you want to learn

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#19]
I think everyone should learn something new from this.
- @Nnichole222 - Because you will be typing this project I think we should use a new technology, which I've already sent out and that would be the use of "Tex" [Capstone Project](https://www.sharelatex.com/project/5791146e197f2f1913025b8b)
  - It's quite easy once you understand the structure
- @elena993  - 
- @Umatrika  -
- @vbruno81  -

**Comment by Nnichole222** [comment]
Your easy is different to my easy.  I tried this program before when you send this to me for MIS 531, it's confusing. Since this is a big paper, I prefer to use Microsoft word. If we can copy and past the paper from word into the program, then we can try that.

**Comment by austinvernsonger** [comment]
It looks confusing, but it's extremely easy. I'm going to create the layout for the document so you won't have to do anything, but put in the words. and this way we can all view the document at any time and also put additional information into it if need be.

**Comment by rozina1** [comment]
can't we use google doc for writing ?

**Comment by austinvernsonger** [comment]
The whole point of this project to put your skills to use and at the same time learn something new. Doing what is easy... Means youre not learning anything new and not taking advantage of the Capstone class. I want our project to be the most documented and detail capstone project. Using git also enables tracking of work done by and who contributed.

**Comment by Umatrika** [comment]
@austinvernsonger : Sounds good to me !!

**Comment by Nnichole222** [comment]
We need to have a team meeting. This is a team project and I understand your ambitions Austin, but this is all over the place @austinvernsonger

**Comment by austinvernsonger** [comment]
@Nnichole222 just direct message me on Slack

**Comment by rozina1** [comment]
i'm ok with this too. And yes we do need a team meeting.
