### ISSUE TITLE
Responsive web design

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#2]
# Responsive web design
- [x] What CSS Framework does it use
## Check
-   [Studiopress](http://www.studiopress.com/responsive/)
-   [Responsinator](http://www.responsinator.com/)

**Comment by Umatrika** [comment]
https://colorlib.com/wp/free-css3-frameworks/

**Comment by elena993** [comment]
food blog theme with eccomerce, simple and clean 
https://themeforest.net/item/food-cook-multipurpose-food-recipe-wp-theme/4915630?ref=cirvitis

**Comment by austinvernsonger** [comment]
Close #2
