### ISSUE TITLE
Customer Support

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#21]
### Prefer URL

[Here's a couple options]

`bodyfuelbydana.slack.com`

`BFBD.slack.com`

`BodyFuelBD.slack.com`

`BFbyDana.slack.com`

**Comment by Umatrika** [comment]
Why Slack account for Dana??

**Comment by austinvernsonger** [comment]
That's what she's going to use for Customer Support.

**Comment by Nnichole222** [comment]
We need dana's email to confirm this slack account.

**Comment by Nnichole222** [comment]
i'm working on this one.

**Comment by Nnichole222** [comment]
Dana is set up with a customer service account for Slack
domain name is BodyfuelBD.slack.com
password is bodyfuel2016
name:is customerservice_bodyfuel
used her gmail to set up the account
bodyfuelbydana@gmail.com
