### ISSUE TITLE
Social Media Accounts

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#22]
## SM
- Ensure Dana personal accounts is separate from business account
  - Have Dana create separate accounts if need be.
  - Ensure personal account is private for search so only her official page account shows up

Social Media sites
- [x] twitter    `[Place URL Here]`
- [x] pintrest    `[Place URL Here]`
- [x] youtube    `[Place URL Here]` 
- [x] facebook     `[Place URL Here]`
- [x] Instagram    `[Place URL Here]`
- [ ] and etc.    `[Place URL Here]`

**Comment by vbruno81** [comment]
I will have this by the end of the day.

**Comment by vbruno81** [comment]
Twitter: https://twitter.com
username and pass-
email: bodyfuelbydana@gmail.com User: dana_bodyfuel Pass: Levi11!!

Pintrest: https://www.pinterest.com/Bodyfuelbydana/
email: danabujalski@gmail.com Pass: Livinglife11

Youtube: https://www.youtube.com/channel/UCD4HfOSYwvR6YfUmMXoLmLwemail: danabujalski@gmail.com Pass: Livinglife11

Facebook (body fuel page): https://www.facebook.com/Body-Fuel-by-Dana-Renee-1513417968962029/?ref=aymt_homepage_panel
email: danabujalski@gmail.com Pass: Bodyfuelbyme112531

Facebook (main page if needed) https://www.facebook.com/dana.bujalski

Instagram: (main) https://www.instagram.com/dana.bujalski/
Instagram (body fuel page) https://www.instagram.com/bodyfuelbydanarenee/
