### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#23]
- [x]  Create  Youtube Channel
- [x]  Add Youtube Channel Art
  - 2560 x 1440 pixels and your file cannot exceed 4 MB
- [x]  Add a channel description and keywords
- [x]  Add links and contact details

Someone needs to be on top of this task and make sure that Dana Completes this.

**Comment by vbruno81** [comment]
I will have all this by the end of the day.
