### ISSUE TITLE
Wordpress Plugins to be Installed and Configured

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#24]
[ I will assign these momentary] 
- [BJ Lazy Load](https://wordpress.org/plugins/bj-lazy-load/) @rozina1  
- [Floating Social](https://premium.wpmudev.org/project/floating-social/) @rozina1  
- [Relevanssi - A Better Search](https://wordpress.org/plugins/relevanssi/) @rozina1  
- [Gallery](https://wordpress.org/plugins/photo-gallery/) @vbruno81 
- [W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/) @Umatrika 1 
- [Jetpack](https://wordpress.org/plugins/jetpack/) @vbruno81 
- [Google XML Sitemaps](https://wordpress.org/plugins/google-sitemap-generator/) @elena993 
- [iThemes Security](https://wordpress.org/plugins/better-wp-security/) @vbruno81 
- [Contact Form 7](https://wordpress.org/plugins/contact-form-7/) @elena993 
- [Google Analytics for WP](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/) @elena993

**Comment by austinvernsonger** [comment]
Wait off on these

**Comment by austinvernsonger** [comment]
### Need the following information for each
- Requirements [if any]
- Installation Information
- Other Information [Optional]
- Last Update Date [Need to make sure we are installing the latest version]

**Comment by vbruno81** [comment]
@vbruno81 

### Sorry.... Had to delete all of that.

Way too much information.... Also I assigned different people for different ones.

One Plugin = One Comment Space.

**Comment by Umatrika** [comment]
W3 Total Cache :  Will do by End of the day.

**Comment by elena993** [comment]
[Contact Form 7 ](https://wordpress.org/plugins/contact-form-7/)
Requirements: 4.3 or higher
Installation Information: 
       Upload the entire contact-form-7 folder to the /wp-content/plugins/ directory.
       Activate the plugin through the 'Plugins' menu in WordPress.
Last Update Date: May 2016

**Comment by elena993** [comment]
[Google Analytics for WP](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/installation/):
Requirements 3.5 or higher
Installation Information:
1.  Upload the full google-analytics-dashboard-for-wp directory into your wp-content/plugins directory.
2.  In WordPress select Plugins from your sidebar menu and activate the Google Analytics Dashboard for WP plugin.
3.  Open the plugin configuration page, which is located under Google Analytics menu.
4.  Authorize the plugin to connect to Google Analytics using the Authorize Plugin button.
5.  Go back to the plugin configuration page, which is located under Google Analytics menu to update/set your settings.
6.  Go to Google Analytics -> Tracking Code to configure/enable/disable tracking.
Other information: Displays Google Analytics reports in your WordPress Dashboard. Inserts the latest Google Analytics tracking code in your pages.
Last Update Date May 2016

**Comment by elena993** [comment]
[Google XML Sitemaps](https://wordpress.org/plugins/google-sitemap-generator/installation/)
Requirements 3.3 or higher
Installation Information:
Install the plugin "Add Plugin" function of WordPress
Activate the plugin at the plugin administration page
Open the plugin configuration page, Settings -> XML-Sitemap and customize settings like priorities and change frequencies. The plugin will automatically update your sitemap of you publish a post
Last Update Date: May 2016

**Comment by vbruno81** [comment]
**Gallery** 
Version: 1.3.4
Author: WebDorado
Last Updated: 2 days ago

Requires WordPress Version: 3.4 or higher
Minimum requirements.

Wordpress 3.4+
PHP 5.x
MySQL 5.x
Perform a new installation

After downloading the ZIP file,

Log in to the administrator panel.
Go to Plugins Add > New > Upload.
Click Choose file (Browse) and select the downloaded zip file of the gallery. For Mac Users Go to your Downloads folder and locate the folder with the gallery plugin. Right-click on the folder and select Compress. Now you have a newly created .zip file which can be installed as described here.
Click Install Now button.
Click Activate Plugin button for activating the gallery plugin.

**Comment by vbruno81** [comment]
**Jetpack**
Version: 4.1.1
Author: Automattic
Last Updated: 4 weeks ago
Requires WordPress Version: 4.4 or higher
Compatible up to: 4.5.3
Install Jetpack from our site by typing in your site address.

Alternatively install Jetpack via the plugin directory, or by uploading the files manually to your server. After activating Jetpack, connect to WordPress.com to enable the Jetpack features.

If you need additional help read our detailed instructions (including a video walkthrough).

**Comment by vbruno81** [comment]
**iThemes Security**
Version: 5.6.0
Author: iThemes
Last Updated: 2 months ago
Requires WordPress Version: 4.1 or higher
Compatible up to: 4.5.3
NOTE: iThemes Security makes significant changers to your database and other site files which can be problematic, so a backup is strongly recommended before making any changes to your site with this plugin. While problems are rare, most support requests involve the failure to make a proper backup before installation.

BEFORE YOU BEGIN: Back up your WordPress database, config file, and .htaccess file. We recommend using BackupBuddy, our WordPress backup plugin for a complete site backup.
Upload the zip file to the /wp-content/plugins/ directory
Unzip
Activate the plugin through the 'Plugins' menu in WordPress
Visit the Security menu for checklist and options
DISCLAIMER: Under no circumstances do we release this plugin with any warranty, implied or otherwise. We cannot be held responsible for any damage that might arise from the use of this plugin.

**Comment by rozina1** [comment]
BJ Lazy Load:
Requires: 3.5 or higher
Compatible up to: 4.3.5
Last Updated: 11 months ago

Installation:
Download and unzip plugin
Upload the 'bj-lazy-load' folder to the '/wp-content/plugins/' directory,
Activate the plugin through the 'Plugins' menu in WordPress.

**Comment by Umatrika** [comment]
w3-total-cache: Easy Web Performance Optimization (WPO) using caching:
browser, page, object, database, minify and content delivery network
support. W3 Total Cache improves the user experience of your site by
increasing server performance, reducing the download times and
providing transparent content delivery network (CDN) integration.

Requirements [if any]: 3.2 or higher and Compatible up to: 4.5.3
Installation Information:
https://wordpress.org/plugins/w3-total-cache/installation/
Other Information [Optional]: Active Installs: 1+ million
Last Update Date [Need to make sure we are installing the latest
version]: 4 months ago

**Comment by rozina1** [comment]
Floating Social:
Requires: 3.4.1 or higher
Compatible up to: 4.1.12
Last Updated: 1 year ago

Installation information:
https://premium.wpmudev.org/wpmu-manual/installing-regular-plugins-on-wpmu/

**Comment by rozina1** [comment]
Relevanssi:

Requires: 4.0 or higher
Compatible up to: 4.5.3
Last Updated: 3 months ago

Installation:
1. Extract all files from the ZIP file, and then upload the plugin's folder to /wp-content/plugins/.
2. If your blog is in English, skip to the next step. If your blog is in other language, rename the file stopwords in the plugin directory as something else or remove it. If there is stopwords.yourlanguage, rename it to stopwords.
3. Activate the plugin through the 'Plugins' menu in WordPress.
4. Go to the plugin settings and build the index following the instructions there.
https://wordpress.org/plugins/relevanssi/installation/

**Comment by austinvernsonger** [comment]
@

**Comment by austinvernsonger** [comment]
closes #24

**Comment by austinvernsonger** [comment]
Please go into the testing environment and play around with the plugins
