### ISSUE TITLE
Wordpress Themes

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#25]
### Find 5 Wordpress Themes Via Github

[Wordpress Themes Github Search](https://github.com/search?o=desc&q=Wordpress+Theme&s=stars&type=Repositories&utf8=%E2%9C%93)

Copy and paste the links in the comment area.

**Comment by elena993** [comment]
https://github.com/bryceadams/Recipe-Hero

**Comment by elena993** [comment]
https://colorlib.com/wp/themes/activello/

**Comment by elena993** [comment]
https://github.com/bestwebsoft/restaurant-advisor-wordpress-theme

**Comment by elena993** [comment]
not github but two themes from upthemes with multiple integrated solutions  
http://demos.upthemes.com/?item=gallery_theme
http://demos.upthemes.com/?item=yumblog_theme

**Comment by vbruno81** [comment]
I like the first one and the last one fell like they would fit the idea the best

**Comment by elena993** [comment]
THe last one is the best, but it costs $125 if she agrees to spend money

**Comment by vbruno81** [comment]
she said she has 300 to spend if it comes down to it she might want to but lets see what we all agree a pond.

**Comment by austinvernsonger** [comment]
# Winner: Brazar Theme
