### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#27]
## Dana will need to purchase a SSL Certificate for credit card processing to protect user personal information
- Encryption of sensitive data like credit card numbers
  and personal information
- Some assurance to your customers that you are trustworthy

**Comment by Nnichole222** [comment]
https://www.symantec.com/page.jsp?id=compare-ssl-certificates&tid=ssl-sem  (most expensive) 

https://www.digicert.com/ppc/ssl-certificate-features.htm?gclid=CImph9Guo84CFQ6PaQodRLEG2w (more affordable and several tiers of pricing options)

https://www.ssls.com/ssl-certificates/comodo-positivessl?years=3 (cheaper ssl, can pay in bitcoin)

https://www.geotrust.com/ssl/# (free trial before purchasing)
