### ISSUE TITLE
Website Layout and Color Scheme

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#29]
# Website Layout & Color Scheme
### Helpful Hints

[Intro to Color Theory For Web Designers](http://webdesign.tutsplus.com/articles/an-introduction-to-color-theory-for-web-designers--webdesign-1437)
[https://www.smashingmagazine.com/web-design-essentials-examples-and-best-practices/](https://www.smashingmagazine.com/web-design-essentials-examples-and-best-practices/)
[http://1stwebdesigner.com/web-design-best-practices/](http://1stwebdesigner.com/web-design-best-practices/)
[10 Rules of Best Practice for Responsive Design](http://thenextweb.com/dd/2015/10/19/10-rules-of-best-practice-for-responsive-design/#gref)

**Comment by elena993** [comment]
https://pixelgrade.com/demos/rosa3/
Check this one

**Comment by elena993** [comment]
I added the following plugins for the theme manipulation
[Customify](https://wordpress.org/plugins/customify/)  - to be bale to use Fonts, Colors, Live CSS Editor 
[PixTypes](https://wordpress.org/plugins/pixtypes/) - custom post types and custom meta boxes from a theme
[PixCodes](https://wordpress.org/plugins/pixcodes/) - to be able to add shortcodes into editor
[Storefront Parallax Hero](https://woocommerce.com/products/storefront-parallax-hero/)

**Comment by austinvernsonger** [comment]
@elena993 Remember..... You post the plugins on here first and then we all approve of them and then you install them.

**Comment by elena993** [comment]
@austinvernsonger I understand, but I was doing all of that at about 3 am, and didn't want to wait till morning. We are working on the testing mode anyway so you can remove any of those if someone against it. They don't affect any functionality, just additional features for customization.
