### ISSUE TITLE
Defensive Design - 404 Pages

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#3]
# Defensive Design
- [x] If a user requests a page that doesn’t exist, your 404 page is displayed
- [A Better 404 page](https://www.smashingmagazine.com/2014/08/a-better-404-page/)

**Comment by Umatrika** [comment]
Message for "404 Page" can be shown something like this: 
Page Not Available... But DANA is. 
Then we can add her contact information so that site users can still contact her and place orders.
