### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#31]
# Content

> We need to make sure the pages in the testing environment has the same content that Dana squarespace site has. This needs to be done ASAP.  This needs to be split up among us so please comment about the pages you want to do.

**Comment by vbruno81** [comment]
I will try my best to just fill in as much as i can, will be in a meeting till noon so limited

**Comment by elena993** [comment]
I can do  How I started and why body Fuel, or whatever you want me to. But I think we should include Blog and Photo Gallery. 
We can replace How I started with About me and add subpages How I started and Photo Gallery

**Comment by austinvernsonger** [comment]
There will be sliders on multiple different pages and She will be able to update as she goes. Photo Gallery are becoming obsolete nowadays, because we can just feed in her Instagram, twitter, and etc.

There already is a blog in the menu.

**Comment by vbruno81** [comment]
Agreed sliders is where its at now adays.
