### ISSUE TITLE
Slack WooCommerce Plugin

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#40]
Configure the settings for this plugin

Need the Slack API information for Dana Slack account.

**Comment by Nnichole222** [comment]
https://api.slack.com/web

**Comment by austinvernsonger** [comment]
Need the Account Slack API information 

On Wed, Aug 24, 2016 at 9:03 PM -0500, "Nnichole222" notifications@github.com wrote:

https://api.slack.com/web
