### ISSUE TITLE
Analytics Tracking

### ISSUE THREAD

**Issue by austinvernsonger** [RMUCapstone-MIS590/Team-A#8]
# Analytics Tracking
## Analytics Platforms
- [Google Analytics](http://www.google.com/analytics/)
- [PIWIK](http://piwik.org/)

**Comment by austinvernsonger** [comment]
## Please who would like to complete this task?

#### Site Account ID: UA-81700475-1
- If you want to then please comment your personal email(google requires personal email account). Then I will add you to the Site's Analytic Account

## Task  - Google Analytics Tracking Code
- [X ] Setup Analytics Account 
- [ ] Add User
- [ ] Get Tracking Code
- [ ] Figure out how to use the tracking code with wordpress
- [ ] Enable It

**Comment by Nnichole222** [comment]
nina.nichole222@gmail.com
